### ISSUE TITLE
Adding a paid advertising medium

### ISSUE THREAD

**Issue by kingo55** [snowplow/referer-parser#130]
A lot of Google Display network traffic just shows up under "unknown", likewise a lot of other display networks show up like this. To use this data in Snowplow, we need to look for mkt_network = 'Google AdWords' and refr_urlhost = 'googleads.g.doubleclick.net'

Do you think it's worth classifying them with referer-parser? Happy to submit a pull request with the changes...

<img width="1011" alt="screen shot 2016-07-15 at 3 17 20 pm" src="https://cloud.githubusercontent.com/assets/2361388/16864384/9d1787a6-4a9f-11e6-8575-4b84c36d6cd2.png">

I suspect we'd need to put some thought into the category naming. e.g. Would we go specific - "display" "cpc" "ppc" or general "advertising"?

**Comment by alexanderdean** [comment]
Interesting idea @kingo55 ! What do the other maintainers think?

**Comment by lstrojny** [comment]
Makes sense from my POV. Would go specific with display, cpc, ppc etc.

**Comment by kingo55** [comment]
@alexanderdean and @lstrojny I've been grouping some of the sites together but I don't think we can reliably specify the type.

For example, Taboola does content marketing but they may also do display through their network

```yaml
display:
  Taboola:
    domains:
      - trc.taboola.com
      - api.taboola.com
```

Do we classify them as "display", "content marketing" or something else? In some ways they sound more like a network than a traffic source.

Thoughts?

**Comment by alexanderdean** [comment]
Hey @lstrojny, @kingo55 - I think the clue is in the ticket name 😄 Anything more specific than "paid" is going to lead to bikeshedding - because we can't precisely capture an advertising company's business model based simply on their referer...

**Comment by kingo55** [comment]
Awesome... that makes things easy then.

Here's a draft I've been working on:

```yaml
paid:

  Google:
    domains:
      - www.googleadservices.com
      - partner.googleadservices.com
      - googleads.g.doubleclick.net
      - tpc.googlesyndication.com
      - googleadservices.com

  Taboola:
    domains:
      - trc.taboola.com
      - api.taboola.com
      - taboola.com

  Criteo:
    domains:
      - cas.jp.as.criteo.com
      - cas.criteo.com

  Doubleclick:
    domains:
      - ad.doubleclick.net
      - ad-apac.doubleclick.net
      - s0.2mdn.net
      - s1.2mdn.net
      - dp.g.doubleclick.net
      - pubads.g.doubleclick.net

  AppNexus:
    domains:
      - ib.adnxs.com
      - adnxs.com
      - 247realmedia.com

  Sizmek:
    domains:
      - bs.serving-sys.com

  PubMatic:
    domains:
      - sshowads.pubmatic.com

  Acuity Ads:
    domains:
      - acuityplatform.com

  OpenX:
    domains:
      - us-ads.openx.net
      - openx.net
      - servedbyopenx.com
      - openxenterprise.com

  Tribal Fusion:
    domains:
      - cdnx.tribalfusion.com

  Eyeota:
    domains:
      - eyeota.net

  Sociomantic Labs:
    domains:
      - sociomantic.com

  ONE by AOL:
    domains:
      - nexage.com

  Neustar AdAdvisor:
    domains:
      - adadvisor.net

  Casale Media:
    domains:
      - casalemedia.com

  BidSwitch:
    domains:
      - bidswitch.net

  StickyADS.tv:
    domains:
      - stickyadstv.com
      - sfx.stickyadstv.com

  Mixpo:
    domains:
      - mixpo.com

  Yieldmo:
    domains:
      - yieldmo.com

  Jivox:
    domains:
      - jivox.com
  Adform:
    domains:
      - adform.net

  Fluct:
    domains:
      - adingo.jp

  AudienceScience:
    domains:
      - wunderloop.net

  MicroAd:
    domains:
      - microad.jp

  LifeStreet:
    domains:
      - lfstmedia.com

  Rubicon Project:
    domains:
      - optimized-by.rubiconproject.com

  SteelHouse:
    domains:
      - steelhousemedia.com

  Sovrn:
    domains:
      - lijit.com

  Sonobi:
    domains:
      - sonobi.com

  ZEDO:
    domains:
      - zedo.com
      - z1.zedo.com

  AdRoll:
    domains:
      - adroll.com

  Flashtalking:
    domains:
      - flashtalking.com
      - servedby.flashtalking.com
  
  Outbrain:
    domains:
      - paid.outbrain.com

  Plista:
    domains:
      - farm.plista.com

  White Pages:
    domains:
      - www.whitepages.com.au
      - mobile.whitepages.com.au

  MyShopping.com.au:
    domains:
      - www.myshopping.com.au

  GetPrice.com.au:
    domains:
      - www.getprice.com.au

  Finder.com.au:
    domains:
      - www.finder.com.au
      - fcc.finder.com.au

  Mozo:
    domains:
      - mozo.com.au
      - a.mozo.com.au

  InfoChoice:
    domains:
      - www.infochoice.com.au
      - keyfactssheet.infochoice.com.au

  RateCity.com.au:
    domains:
      - ratecity.com.au
      - direct.ratecity.com.au
      - www.ratecity.com.au
```
